# Generated by Django 5.2.7 on 2025-10-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('std_id', models.IntegerField(primary_key=True, serialize=False)),
                ('std_name', models.CharField(max_length=50)),
                ('std_pic', models.FileField(upload_to='profile/')),
            ],
        ),
    ]
