# Generated by Django 5.2.8 on 2025-11-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_app', '0003_cloudtable_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudtable',
            name='password',
            field=models.CharField(default='123456', max_length=8),
        ),
    ]
