# Generated by Django 5.2.8 on 2025-11-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_app', '0004_cloudtable_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudtable',
            name='password',
            field=models.CharField(default='123456', max_length=255),
        ),
    ]
