# Generated by Django 5.2.7 on 2025-10-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_mail', models.CharField(default='emp@org.in', max_length=50)),
                ('emp_num', models.CharField(max_length=10)),
            ],
        ),
    ]
